apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: ipfs-counter

resources:
- kubernetes.yml
images:
- name: gcr.io/PROJECT_ID/IMAGE:TAG
  newName: gcr.io/blah/hello
  newTag: "1"
